export { default as Home } from './home'
export { default as Login } from './login'
export { default as Favorites } from './favorites'
export { default as Register } from './register'
export { default as Profile } from './profile'
export { default as Detail } from './detail'
export { default as Categories } from './categories'
export { default as CategoryGames } from './category-games'
